name: Package
on:
  workflow_call:
    inputs:
      version:
        description: GetHub package version
        required: true
        type: string
jobs:
  windows:
    name: Package Windows
    runs-on: windows-2022
    strategy:
      matrix:
        runtime: [win-x64, win-arm64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: gethub.${{ matrix.runtime }}
          path: build/GetHub
      - name: Package
        shell: pwsh
        env:
          VERSION: ${{ inputs.version }}
          RUNTIME: ${{ matrix.runtime }}
        run: ./build/scripts/package.win.ps1
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: package.${{ matrix.runtime }}
          path: build/gethub_*.zip
      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: gethub.${{ matrix.runtime }}
  osx-app:
    name: Package macOS
    runs-on: macos-latest
    strategy:
      matrix:
        runtime: [osx-x64, osx-arm64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: gethub.${{ matrix.runtime }}
          path: build
      - name: Package
        env:
          VERSION: ${{ inputs.version }}
          RUNTIME: ${{ matrix.runtime }}
        run: |
          mkdir build/GetHub
          tar -xf "build/gethub.${{ matrix.runtime }}.tar" -C build/GetHub
          ./build/scripts/package.osx-app.sh
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: package.${{ matrix.runtime }}
          path: build/gethub_*.zip
      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: gethub.${{ matrix.runtime }}
